" activate pathogen plugin
call pathogen#infect()
call pathogen#helptags()

set nocompatible                                  " use vim settings
set backspace=indent,eol,start                    " allow backspacing in insert mode
set t_Co=256                                      " use term with 256 colors
set showcmd                                       " display incomplete commands
set showmode                                      " display the current mode
set number                                        " display line numbers
set incsearch                                     " highlight matches as you type
set hlsearch                                      " highlight matches
set ignorecase                                    " case-insensitive searching
set smartcase                                     " but case-sensitive if expression contains a capital letter
set cursorline                                    " highligth the current line
set ruler                                         " display cursor position
set title                                         " set the terminal's title
set mouse=a                                       " use mouse to resize splitted windows
set visualbell                                    " no beep
set splitbelow                                    " open window below current window
set wrap                                          " turn on line wrapping
set linebreak                                     " wrap line at convenient points
set wildmenu                                      " enhanced command line completion
set wildmode=list:longest                         " complete files like a shell
set hidden                                        " handle better multiple buffers
set modifiable                                    " allow modifications to the buffer
set nobackup                                      " don't make a backup before overwriting a file
set nowritebackup                                 " and again
set directory=$HOME/.vim/tmp//,.                  " keep swap files in one location
set scrolloff=3                                   " show 3 lines above/below the cursor
syn on                                            " turn on syntax highlighting
filetype plugin indent on                         " turn on file type detection

" colorscheme
" Mac OS X : import ~/.vim/osx/iterm-modified-solarized.itermcolors in iterm2
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

" default indent settings
set tabstop=2                                     " global tab width
set shiftwidth=2                                  " and again, related
set softtabstop=2                                 " equal shiftwidth & tabstop
set smarttab                                      " smart handling of the <tab> key
set expandtab                                     " use spaces instead of tabs
set autoindent
set listchars=trail:·,tab:▸\ ,eol:¬,extends:>     " tab if no « set expandtab »

" statusline setup
" useful status information at bottom of screen
set statusline=[%n]
set statusline+=[%f]
set statusline+=%h
set statusline+=%w
set statusline+=%m
set statusline+=%r
set statusline+=%y
" display a warning if fileformat isn't unix
set statusline+=%#warningmsg#
set statusline+=%{&ff!='unix'?'['.&ff.']':''}
set statusline+=%*
" display a warning if file encoding isn't utf-8
set statusline+=%#warningmsg#
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%*
" display a warning if paste is set
set statusline+=%#error#
set statusline+=%{&paste?'[paste]':''}
set statusline+=%*
" display line/column infos and percent through file
set statusline+=%=                                " left/right separator
set statusline+=%c,                               " cursor column
set statusline+=%l/%L                             " cursor line/total lines
set statusline+=\ %P                              " percent through file
set laststatus=2                                  " nb of status lines

" redefine map leader
let mapleader = ","

" shortcut to rapidly toggle « set list » & « set paste »
nmap <leader>l :set list!<cr>
nmap <leader>p :set paste!<cr>

" personal shortcuts
" stop highlight matches with enter
nnoremap <cr> :nohlsearch<cr>/<bs>
